import Layout from "@/components/Layout";
import Head from "next/head";
import ProfilePic from "../../public/images/profile/developer-pic.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className='pt-0 pl-[3%]'>
          <div className="flex items-center justify-between w-full">
            <div className='w-[40%]'>
              <Image
                src={ProfilePic}
                alt="JayPrajapati"
                className="w-full h-auto"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center '>
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className="!text-6xl !text-left"/>
              <p className='my-4 text-base font-medium'>
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link href="/" target="_blank" className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark" download={true}>Resume</Link>

                <Link href="/contact" className="ml-4 text-lg font-medium capitalize flex items-center bg-light text-dark p-2.5 px-6 rounded-lg border-2 border-solid border-dark">Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8
        bottom-8 inline-block w-24">
          <Image src={lightBulb} alt="Jay Prajapati" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
