import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import { ContactImg } from "@/components/Icons";
import TransitionEffect from "@/components/TransitionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>{`Jay Prajapati | Home`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className='pt-0 md:pt-16 sm:pt-8 pl-[3%]'>
          <div className="flex items-center justify-between w-full xl:flex-col">
            <div className='w-[40%] md:w-full'>
            <ContactImg 
            className="lg:hidden md:inline-block md:w-full" />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center xl:w-full xl:text-center'>
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className="!text-6xl xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl mb-2 items-center justify-center"/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
              {`As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.`}
              </p>
              <div className="flex items-center self-start mt-2 2xl:self-center">
                <Link href="/" target="_blank" className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light" download={true}>Resume</Link>

                <Link href="/contact" className="ml-4 text-lg font-medium capitalize flex items-center bg-light text-dark p-2.5 px-6 rounded-lg border-2 border-solid border-dark dark:text-light dark:bg-dark dark:border-light">Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <div className="absolute right-8
        bottom-2 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="Jay Prajapati" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
